'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { startBackend } = require('../backend/server');
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'azurecord-v52-'));
const file = path.join(temp, 'azurecord.json');
async function api(base, route, token, method='GET', body) {
 const response=await fetch(base+route,{method,headers:{ ...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{}) },body:body?JSON.stringify(body):undefined});
 let data=await response.json();return {status:response.status,...data};
}
test('V52 beta: auth, privacy, invites, messaging, memory, feedback, persistence',async t=>{
 let started=await startBackend({host:'127.0.0.1',port:0,dataFile:file});
 let base='http://127.0.0.1:'+started.address.port;
 t.after(async()=>{if(started)await started.backend.close();fs.rmSync(temp,{recursive:true,force:true});});
 assert.equal((await api(base,'/api/health')).version,52);
 assert.equal((await api(base,'/api/auth/signup',null,'POST',{email:'bad',password:'12345678',username:'wrong'})).status,400);
 const alice=await api(base,'/api/auth/signup',null,'POST',{email:'alice@test.dev',password:'StrongPass!1',username:'alice'});
 const bob=await api(base,'/api/auth/signup',null,'POST',{email:'bob@test.dev',password:'StrongPass!2',username:'bob'});
 assert.equal(alice.status,201);assert.equal(bob.status,201);
 assert.equal((await api(base,'/api/me',alice.token)).user.email,'alice@test.dev');
 assert.equal((await api(base,'/api/users',alice.token)).users?.find(x=>x.id===bob.user.id)?.email,undefined);
 const created=await api(base,'/api/servers',alice.token,'POST',{name:'Beta studio'});
 assert.equal(created.status,201);
 const sid=created.server.id,cid=created.channels[0].id;
 assert.equal((await api(base,`/api/servers/${sid}/channels/${cid}/messages`,bob.token)).status,403);
 const joined=await api(base,'/api/servers/join',bob.token,'POST',{code:created.server.invite});
 assert.equal(joined.status,201);
 const sent=await api(base,`/api/servers/${sid}/channels/${cid}/messages`,bob.token,'POST',{text:'Olá, comunidade!',clientId:'once'});
 assert.equal(sent.status,201);
 assert.equal((await api(base,`/api/servers/${sid}/channels/${cid}/messages`,bob.token,'POST',{text:'Olá, comunidade!',clientId:'once'})).duplicate,true);
 assert.equal((await api(base,`/api/servers/${sid}/channels/${cid}/messages`,alice.token)).messages.length,1);
 assert.equal((await api(base,'/api/ai/memory',bob.token)).status,200);
 assert.equal((await api(base,'/api/beta/feedback',bob.token,'POST',{category:'bug',description:'A janela demorou para abrir.'})).status,201);
 assert.equal((await api(base,'/api/beta/feedback',alice.token)).status,403);
 const direct=await api(base,`/api/dms/${bob.user.id}/messages`,alice.token,'POST',{text:'Mensagem particular'});
 assert.equal(direct.status,201);
 assert.equal((await api(base,`/api/dms/${alice.user.id}`,bob.token)).messages.length,1);
 assert.equal((await api(base,`/api/dms/${bob.user.id}`,alice.token,'DELETE')).removed,1);
 assert.equal((await api(base,`/api/dms/${bob.user.id}`,alice.token)).messages.length,0);
 assert.equal((await api(base,`/api/dms/${alice.user.id}`,bob.token)).messages.length,1);
 await started.backend.close();started=null;
 started=await startBackend({host:'127.0.0.1',port:0,dataFile:file});base='http://127.0.0.1:'+started.address.port;
 assert.equal((await api(base,`/api/servers/${sid}/channels/${cid}/messages`,alice.token)).messages.length,1);
 assert.equal((await api(base,`/api/dms/${alice.user.id}`,bob.token)).messages.length,1);
 assert.equal(started.backend.store.db.betaFeedback.length,1);
 assert.equal(fs.existsSync(file),true);
});
