'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {startBackend}=require('../backend/server');
const {settings,wallet}=require('../backend/azure-points');

const envKeys=['AZURECORD_POINTS_PER_BRL','AZURECORD_POINTS_MIN_REDEEM','AZURECORD_POINTS_CASHOUT_ENABLED','AZURECORD_POINTS_ADMIN_EMAIL','AZURECORD_POINTS_ADMIN_KEY','AZURECORD_BETA_ADMIN_EMAIL'];
async function call(base,route,token=null,method='GET',body=null,extra={}){
  const res=await fetch(base+route,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{}),...extra},body:body?JSON.stringify(body):undefined});
  return {status:res.status,...await res.json()};
}
test('AzurePoints: créditos legítimos, loja vazia, saldo privado, resgate reservado, aprovação manual e reinício',async t=>{
  const old=Object.fromEntries(envKeys.map(k=>[k,process.env[k]]));
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'azurepoints-'));
  let running=null;
  t.after(async()=>{if(running)await running.backend.close();for(const [key,value] of Object.entries(old)){if(value===undefined)delete process.env[key];else process.env[key]=value;}fs.rmSync(dir,{recursive:true,force:true});});
  process.env.AZURECORD_POINTS_CASHOUT_ENABLED='false';
  process.env.AZURECORD_POINTS_PER_BRL='100';
  process.env.AZURECORD_POINTS_MIN_REDEEM='500';
  delete process.env.AZURECORD_POINTS_ADMIN_EMAIL;delete process.env.AZURECORD_POINTS_ADMIN_KEY;
  const file=path.join(dir,'database.json');
  running=await startBackend({host:'127.0.0.1',port:0,dataFile:file});
  let base='http://127.0.0.1:'+running.address.port;
  const alice=await call(base,'/api/auth/signup',null,'POST',{email:'alice@points.test',password:'StrongPass123',username:'pointsalice'});
  const bob=await call(base,'/api/auth/signup',null,'POST',{email:'bob@points.test',password:'StrongPass123',username:'pointsbob'});
  const admin=await call(base,'/api/auth/signup',null,'POST',{email:'admin@points.test',password:'StrongPass123',username:'pointsadmin'});
  assert.equal(alice.status,201);assert.equal(bob.status,201);assert.equal(admin.status,201);
  const w1=await call(base,'/api/points/wallet',alice.token);
  assert.deepEqual(w1.wallet,{earned:100,reserved:0,available:100});
  assert.equal(w1.cashoutEnabled,false);
  assert.deepEqual((await call(base,'/api/points/shop',alice.token)).items,[]);
  assert.equal((await call(base,'/api/points/redemptions',alice.token,'POST',{points:500,clientRequestId:'abc123456789'})).status,503);
  assert.equal((await call(base,'/api/points/credits',bob.token,'POST',{points:999999})).status,404);
  const f1=await call(base,'/api/beta/feedback',alice.token,'POST',{category:'bug',description:'Falha ao abrir a tela de perfil quando há muitas pessoas.'});
  const f2=await call(base,'/api/beta/feedback',alice.token,'POST',{category:'bug',description:'Falha ao abrir a tela de perfil no segundo teste.'});
  assert.equal(f1.azurePointsAwarded,15);assert.equal(f2.azurePointsAwarded,0);
  assert.equal((await call(base,'/api/points/wallet',alice.token)).wallet.available,115);
  assert.equal((await call(base,'/api/points/history',bob.token)).entries.length,1,'bob não recebe histórico da alice');

  process.env.AZURECORD_POINTS_ADMIN_EMAIL='admin@points.test';
  process.env.AZURECORD_POINTS_ADMIN_KEY='private-test-admin-key';
  process.env.AZURECORD_POINTS_CASHOUT_ENABLED='true';
  assert.equal(settings().cashoutEnabled,true);
  const adminHeaders={'X-Azurecord-Admin-Key':'private-test-admin-key'};
  const creditBody={userId:alice.user.id,points:1000,reason:'Prêmio por participação no beta',clientRequestId:'approved_beta_credit_1'};
  assert.equal((await call(base,'/api/admin/points/credits',alice.token,'POST',creditBody,adminHeaders)).status,403,'usuário comum não se torna admin com a chave');
  assert.equal((await call(base,'/api/admin/points/credits',admin.token,'POST',creditBody)).status,403,'email admin sem chave não basta');
  const credit=await call(base,'/api/admin/points/credits',admin.token,'POST',creditBody,adminHeaders);
  assert.equal(credit.status,201);
  assert.equal((await call(base,'/api/admin/points/credits',admin.token,'POST',creditBody,adminHeaders)).duplicate,true);
  assert.equal((await call(base,'/api/points/wallet',alice.token)).wallet.available,1115);
  assert.equal((await call(base,'/api/points/redemptions',bob.token,'POST',{points:500,clientRequestId:'redeem_bob_0001'})).status,409,'sem pontos não pode fazer resgate');
  const cashout=await call(base,'/api/points/redemptions',alice.token,'POST',{points:600,clientRequestId:'redeem_alice_0001'});
  assert.equal(cashout.status,201);assert.equal(cashout.redemption.amountCentavos,600);
  assert.equal(cashout.wallet.available,515);assert.equal(cashout.wallet.reserved,600);
  assert.equal((await call(base,'/api/points/redemptions',alice.token,'POST',{points:600,clientRequestId:'redeem_alice_0001'})).duplicate,true);
  const pending=await call(base,'/api/admin/points/redemptions?status=pending',admin.token,'GET',null,adminHeaders);
  assert.equal(pending.redemptions.length,1);
  assert.equal(pending.redemptions[0].userId,alice.user.id);
  assert.equal((await call(base,'/api/admin/points/redemptions/'+cashout.redemption.id+'/paid',admin.token,'POST',{},adminHeaders)).status,400,'pagamento exige comprovante externo');
  const paid=await call(base,'/api/admin/points/redemptions/'+cashout.redemption.id+'/paid',admin.token,'POST',{receipt:'external-payment-ref-123456'},adminHeaders);
  assert.equal(paid.status,200);assert.equal(paid.redemption.status,'paid');
  assert.equal((await call(base,'/api/admin/points/redemptions/'+cashout.redemption.id+'/paid',admin.token,'POST',{receipt:'again-123456'},adminHeaders)).status,409);
  assert.deepEqual((await call(base,'/api/points/wallet',alice.token)).wallet,{earned:515,reserved:0,available:515});
  const second=await call(base,'/api/points/redemptions',alice.token,'POST',{points:500,clientRequestId:'redeem_alice_0002'});
  assert.equal(second.status,201);
  assert.equal((await call(base,'/api/points/wallet',alice.token)).wallet.available,15);
  const reject=await call(base,'/api/admin/points/redemptions/'+second.redemption.id+'/reject',admin.token,'POST',{reason:'Revisão administrativa'},adminHeaders);
  assert.equal(reject.redemption.status,'rejected');
  assert.equal((await call(base,'/api/points/wallet',alice.token)).wallet.available,515);
  await running.backend.close();running=null;
  running=await startBackend({host:'127.0.0.1',port:0,dataFile:file});base='http://127.0.0.1:'+running.address.port;
  assert.equal((await call(base,'/api/points/wallet',alice.token)).wallet.available,515,'saldo persistiu no reinício');
  assert.equal((await call(base,'/api/points/redemptions',alice.token)).redemptions.length,2);
  assert.equal(running.backend.store.db.pointsLedger.filter(e=>e.userId===alice.user.id&&e.reason==='credito-administrativo').length,1);
});

test('DM: deduplicação por clientId, remetente verificado, persistência e evento ao destinatário',async t=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'azurecord-dm-idempotency-'));
  let running=await startBackend({host:'127.0.0.1',port:0,dataFile:path.join(dir,'data.json')});
  t.after(async()=>{if(running)await running.backend.close();fs.rmSync(dir,{recursive:true,force:true});});
  const base='http://127.0.0.1:'+running.address.port;
  const alice=await call(base,'/api/auth/signup',null,'POST',{email:'dmalice@sample.test',password:'StrongPass123',username:'dmtestalice'});
  const bob=await call(base,'/api/auth/signup',null,'POST',{email:'dmbob@sample.test',password:'StrongPass123',username:'dmtestbob'});
  const emitted=[];const originalEmit=running.backend.emit.bind(running.backend);
  running.backend.emit=(to,event,data)=>{emitted.push({to,event,data});originalEmit(to,event,data);};
  const clientId='client-message-retry-123';
  const msg1=await call(base,`/api/dms/${bob.user.id}/messages`,alice.token,'POST',{text:'Bom dia, Bob!',clientId,senderId:bob.user.id});
  assert.equal(msg1.status,201);assert.equal(msg1.message.senderId,alice.user.id);assert.equal(msg1.message.clientId,clientId);
  const msg2=await call(base,`/api/dms/${bob.user.id}/messages`,alice.token,'POST',{text:'Bom dia, Bob!',clientId});
  assert.equal(msg2.duplicate,true);assert.equal(msg2.message.id,msg1.message.id);
  assert.equal((await call(base,`/api/dms/${alice.user.id}`,bob.token)).messages.length,1);
  assert.equal((await call(base,`/api/dms/${bob.user.id}`,alice.token)).messages.length,1);
  const pushed=emitted.find(e=>e.event==='dm.message');
  assert.equal(pushed.to,bob.user.id);assert.equal(pushed.data.user.username,alice.user.username);
  assert.equal((await call(base,'/api/dms/user-phantom/messages',alice.token,'POST',{text:'oi'})).status,404);
});
