name = "azurecord-api"
main = "worker-v0.9.1.js"
compatibility_date = "2026-10-01"

[[d1_databases]]
binding = "DB"
database_name = "azurecord-prod"
database_id = "597184ae-2c7b-423c-a4a4-b79721f95fe6"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "azurecord-attachments"
